# https://medium.com/@mpaternostro/how-to-deploy-pages-on-github-using-actions-a9281d03b345
name: Build and deploy pages
run-name: Build and deploy pages

on: [ push, workflow_dispatch ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup java (required by clojure)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # use appropriate distribution
          java-version: '21' # use appropriate version

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463 # use appropriate version

      - name: Check out current repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build pages with custom alias
        run: clojure -X:export

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages # Must use this name
          path: ./out

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4